# Generated by Django 2.0.2 on 2022-03-11 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interfacetestplatform', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Register',
        ),
    ]
